[workspace]
members = [ "package-updater" ]
resolver = "2"

[workspace.package]
version = "1.0.0"

[workspace.metadata.crane]
name = "cosmic-ext-applet-package-updater"

[profile.release]
lto = "fat"

[workspace.lints.clippy]
todo = "warn"
unwrap_used = "warn"
